spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: chat-application

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
