spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: chat-application

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-late-sunset-a8mzvpqs-pooler.eastus2.azure.neon.tech/ChatApp?user=neondb_owner&password=npg_8qXA1hWgEzCJ&sslmode=require}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5000,https://realchatapplicaton.onrender.com}
