name: API Health Check

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://realchatapplicaton.onrender.com/)
          if [ "$response" -eq 200 ]; then
            echo "API is up and running!"
          else
            echo "API returned status code $response"
          fi
